name: tictactoe_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.3+1
  provider: ^6.1.2
  firebase_core: ^2.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/tictactoe.gif
